#!/bin/sh
#
# Plugin to monitor the state / freshness  of the tiles returned by mod_tile
#
# Parameters:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# Copyright (c) 2007 - 2023 by mod_tile contributors (see AUTHORS file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; If not, see http://www.gnu.org/licenses/.

if [ "$1" = "config" ]; then

  echo 'graph_title freshness of served tiles'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel tiles per ${graph_period}'
  echo 'graph_category mod_tile'
  echo 'fresh.label Fresh from disk'
  echo 'fresh.draw AREA'
  echo 'fresh.type DERIVE'
  echo 'fresh.min 0'
  echo 'freshrender.label Freshly rendered'
  echo 'freshrender.draw STACK'
  echo 'freshrender.type DERIVE'
  echo 'freshrender.min 0'
  echo 'old.label Old from disk'
  echo 'old.draw STACK'
  echo 'old.type DERIVE'
  echo 'old.min 0'
  echo 'oldrender.label Old tile, attempted render'
  echo 'oldrender.draw STACK'
  echo 'oldrender.type DERIVE'
  echo 'oldrender.min 0'
  echo 'outdated.label Outdated from disk'
  echo 'outdated.draw STACK'
  echo 'outdated.type DERIVE'
  echo 'outdated.min 0'
  echo 'outdatedrender.label Outdated tile, attempted render'
  echo 'outdatedrender.draw STACK'
  echo 'outdatedrender.type DERIVE'
  echo 'outdatedrender.min 0'

  exit 0
fi

data=$(wget -q ${MOD_TILE_URL:-http://localhost/mod_tile} -O -)

fresh=$(expr match "$data" '.*NoFreshCache: \([0-9]*\)')
freshRender=$(expr match "$data" '.*NoFreshRender: \([0-9]*\)')
old=$(expr match "$data" '.*NoOldCache: \([0-9]*\)')
oldRender=$(expr match "$data" '.*NoOldRender: \([0-9]*\)')
outdated=$(expr match "$data" '.*NoVeryOldCache: \([0-9]*\)')
outdatedRender=$(expr match "$data" '.*NoVeryOldRender: \([0-9]*\)')

echo "fresh.value " $fresh
echo "freshrender.value " $freshRender
echo "old.value " $old
echo "oldrender.value " $oldRender
echo "outdated.value " $outdated
echo "outdatedrender.value " $outdatedRender
