#!/bin/sh
#
# Plugin to monitor the response codes of tiles returned by mod_tile
#
# Parameters:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#
# Copyright (c) 2007 - 2023 by mod_tile contributors (see AUTHORS file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; If not, see http://www.gnu.org/licenses/.

if [ "$1" = "config" ]; then

  echo 'graph_title mod_tile HTTP response codes'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel responses per ${graph_period}'
  echo 'graph_category mod_tile'
  echo 'response200.label 200 OK'
  echo 'response200.draw AREA'
  echo 'response200.type DERIVE'
  echo 'response200.min 0'
  echo 'response304.label 304 Not Modified'
  echo 'response304.draw STACK'
  echo 'response304.type DERIVE'
  echo 'response304.min 0'
  echo 'response404.label 404 Not Found'
  echo 'response404.draw STACK'
  echo 'response404.type DERIVE'
  echo 'response404.min 0'
  echo 'response500.label 500 Internal Error'
  echo 'response500.draw STACK'
  echo 'response500.type DERIVE'
  echo 'response500.min 0'

  exit 0
fi

data=$(wget -q ${MOD_TILE_URL:-http://localhost/mod_tile} -O -)

ok_resp=$(expr match "$data" '.*NoResp200: \([0-9]*\)')
nm_resp=$(expr match "$data" '.*NoResp304: \([0-9]*\)')
fnf_resp=$(expr match "$data" '.*NoResp404: \([0-9]*\)')
error_resp=$(expr match "$data" '.*NoResp5XX: \([0-9]*\)')

echo "response200.value " $ok_resp
echo "response304.value " $nm_resp
echo "response404.value " $fnf_resp
echo "response500.value " $error_resp
