---
dist: focal
language: cpp

compiler:
  - clang

services:
  - docker

before_install:
  - sudo apt update -y

jobs:
  include:
    - stage: code formatting
      install:
        - sudo apt -y install astyle
      script:
        - astyle --options=none --lineend=linux --style=1tbs --indent=force-tab=8 --break-blocks --indent-switches --pad-oper --pad-header --unpad-paren --suffix=none includes/* src/*
        - |
          if [[ -n $(git diff) ]]; then
            echo "You must run 'astyle --options=none --lineend=linux --style=1tbs --indent=force-tab=8 --break-blocks --indent-switches --pad-oper --pad-header --unpad-paren --suffix=none includes/* src/*' before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi
    - stage: tests
      install:
        - sudo apt -y install apache2-dev libcairo2-dev libcurl4-gnutls-dev libglib2.0-dev libiniparser-dev libmapnik-dev
      script:
        - ./autogen.sh
        - ./configure
        - make
        - make test
    - stage: mod_tile test
      install:
        - docker build -t mod_tile .
        - docker run --detach --publish 8080:80 mod_tile
      script:
        - docker run --rm --entrypoint /bin/bash mod_tile -c "make test"
        - curl --silent http://localhost:8080/renderd-example/tiles/9/297/191.png | sha256sum - | grep dbf26531286e844a3a9735cdd193598dca78d22f77cafe5824bcaf17f88cbb08
