#!/bin/sh
#
# Plugin to monitor the state / freshness  of the tiles returned by mod_tile
#
# Parameters: 
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [ "$1" = "config" ]; then

	echo 'graph_title latency of tile retrival from disk'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel latency in ms'
	echo 'graph_category mod_tile'
	echo 'total.label All served tiles'
	echo 'total.draw LINE2'
	echo 'total.type GAUGE'
	echo 'total.min 0'

	exit 0
fi

#MUNIN_STATEFILE=latency.state

data=`wget -q http://localhost/mod_tile -O -`


totalDuration=`expr match "$data" '.*DurationTileBufferReads: \([0-9]*\)'`
noTotal=`expr match "$data" '.*NoTileBufferReads: \([0-9]*\)'`
totalDurationPrev=`sed -e '/^DurationTileBufferReads/!d' -e 's/.*: //' -e q $MUNIN_STATEFILE`
noTotalPrev=`sed -e '/^NoTileBufferReads/!d' -e 's/.*: //' -e q $MUNIN_STATEFILE`

echo "DurationTileBufferReads: $totalDuration" > $MUNIN_STATEFILE
echo "NoTileBufferReads: $noTotal" >> $MUNIN_STATEFILE


if [ "$noTotal" = "$noTotalPrev" ];
then
    totalLatency=0
else
    totalLatency=$(echo "$totalDuration $totalDurationPrev $noTotal $noTotalPrev" | awk '{ totalLat = ($1 - $2) / ($3 - $4) / 1000.0; print totalLat}' )
fi

echo "total.value " $totalLatency
