#!/bin/bash

while (/bin/true)
do
  ymd=`date +%y%m%d`
#  ymd="071031"

  file="planet-${ymd}.osm.gz"
  name="/home/www/tile/direct/planet/${file}"   
  url="http://planet.openstreetmap.org/${file}"

  if [ -s "${name}" ]
  then
    echo "$name Already exists"
    exit 1
  fi

  date
  echo "Fetching: $file"

  wget -O "${name}" "${url}"
  if [ $? -ne 0 ]; then
      echo "failed"
      sleep 600
  else 
      echo "Planet Downloaded OK"
      killall -w renderd
      # Some zlib fail with files > 2GB, gzip seems OK
      gzip -dc "${name}" | time osm2pgsql -m -
      if [ $? -ne 0 ]; then
	  echo "Problem importing data"
	  exit 1
      fi

      sleep 5

      /home/jburgess/svn.openstreetmap.org/applications/utils/mod_tile/renderd &
      touch /tmp/planet-import-complete
      echo "Rendering restarted OK"

      sleep 5

      cd /home/jburgess/svn.openstreetmap.org/applications/utils/mod_tile/old
      rm -fR `seq 0 18`
      mkdir `seq 0 18`
      ./render_all
      echo "render_all started"
      exit 0
  fi
done
exit -1
