#!/bin/bash

# Copyright © 2013 mod_tile contributors
#
# This file is part of mod_tile.
#
# mod_tile is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 2 of the License, or (at your
# option) any later version.
#
# mod_tile is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with mod_tile.  If not, see <http://www.gnu.org/licenses/>.

while (/bin/true)
do
  ymd=`date +%y%m%d`
#  ymd="071031"

  file="planet-${ymd}.osm.gz"
  name="/home/www/tile/direct/planet/${file}"   
  url="http://planet.openstreetmap.org/${file}"

  if [ -s "${name}" ]
  then
    echo "$name Already exists"
    exit 1
  fi

  date
  echo "Fetching: $file"

  wget -O "${name}" "${url}"
  if [ $? -ne 0 ]; then
      echo "failed"
      sleep 600
  else 
      echo "Planet Downloaded OK"
      killall -w renderd
      # Some zlib fail with files > 2GB, gzip seems OK
      gzip -dc "${name}" | time osm2pgsql -m -
      if [ $? -ne 0 ]; then
	  echo "Problem importing data"
	  exit 1
      fi

      sleep 5

      /home/jburgess/svn.openstreetmap.org/applications/utils/mod_tile/renderd &
      touch /tmp/planet-import-complete
      echo "Rendering restarted OK"

      sleep 5

      cd /home/jburgess/svn.openstreetmap.org/applications/utils/mod_tile/old
      rm -fR `seq 0 18`
      mkdir `seq 0 18`
      ./render_all
      echo "render_all started"
      exit 0
  fi
done
exit -1
