---
inputs:
  packages:
    description: List of package(s) to install
    required: true

runs:
  using: composite
  steps:
    - name: Install package(s)
      run: yum --assumeyes install ${{ inputs.packages }}
      shell: bash
