.TH RENDER_EXPIRED 1 "Jan 27, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
render_expired \- expires a list of map tiles so that they get re-rendered.
.SH SYNOPSIS
.B render_expired
.RI [ options ] <  "expire.list"
.br
.SH DESCRIPTION
This manual page documents briefly the
.B render_expired
command.
.PP
.B render_expired
is a helper utility that takes a list of map tiles from stdin and expires them such that they will get re-rendered.
Render_expired has three potential strategies of how to expire map tiles:
.br
1) Render tiles directly: Render_expired can connect to the renderd socket and submit rendering requests for expired tiles directly
.br
2) Delete tiles: Render_expired can delete expired tiles from disk. The next time the tile then gets viewed it will get re-rendered, assuming a dynamic rendering setup like mod_tile is installed
.br
3) Mark tiles as dirty: A dynamic tile rendering system like mod_tile decides if a tile needs re-rendering by comparing the timestamp of the tile with the time of the planet-import-complet timestamp. Render_expired can set the timestamp of a tile back many years, ensuring it is older than the db import time, thus causeing the tile to be considered dirty and in need for re-render.
.PP
These three strategies can be combined and applied at different zoom levels. E.g. Zoom level 17-18 get deleted, z11 - z16 get marked dirty and z6 - z10 get rendered directly.
.PP
Render_expired takes a list of tiles from stdin which should be expired. The format of the list is one tile per line specified as z/x/y.
.br
1/0/1
.br
1/1/1
.br
1/0/0
.br
1/1/0
.PP
render_expired will automatically expand the list to cover the effected tiles at other zoom levels.
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
\fB\-m\fR|\-\-map=MAP
Specify the style-sheet for which to expire tiles. The default is "default".
.TP
\fB\-s\fR|\-\-socket=SOCKET
Specify the location of the renderd socket.
.TP
\fB\-n\fR|\-\-num-threads=N
Specify the number of parallel requests to renderd. Should renderd have less threads active, requests will be queued. The default is 1.
default if \fB\-\-append\fR is not specified.
.TP
\fB\-t\fR|\-\-tiledir=DIR
Specify the base directory where the rendered tiles are. The default is '/var/lib/mod_tile'
.TP
\fB\-z\fR|\-\-min-zoom=ZOOM
Filter input to only render tiles greater or equal to this zoom level (default is 0)
.TP
\fB\-Z\fR|\-\-max-zoom=ZOOM
Filter input to only render tiles less than or equal to this zoom level (default is 18)
.TP
\fB\-d\fR|\-\-delete-from=ZOOM
When expiring tiles of ZOOM or higher, delete them instead of re-rendering (default is off)
.TP
\fB\-T\fR|\-\-touch-from=ZOOM
when expiring tiles of ZOOM or higher, touch them instead of re-rendering (default is off)
.PP
.SH SEE ALSO
.BR renderd (1),
.BR mod_tile (1).
.br
.SH AUTHOR
render_expire was written by OpenStreetMap project members.
.PP
This manual page was written by OpenStreetMap authors.
