---
inputs:
  packages:
    description: List of package(s) to install
    required: true

runs:
  using: composite
  steps:
    - name: Install package(s)
      run: brew install ${{ inputs.packages }}
      shell: bash --noprofile --norc -euxo pipefail {0}
