---
inputs:
  build-dependencies:
    default:  >-
      apache24
      cairo
      ceph14
      cmake
      coreutils
      curl
      glib
      iniparser
      libmemcached
      mapnik
      pkgconf
    description: List of build dependency package(s) to install

runs:
  using: composite
  steps:
    - name: Install dependencies, Build, Test & Install `mod_tile`
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        mem: 4096
        prepare: |
          mkdir -p /usr/local/etc/pkg/repos
          sed 's#/quarterly#/latest#g' /etc/pkg/FreeBSD.conf > /usr/local/etc/pkg/repos/FreeBSD.conf
          pkg upgrade --yes
          pkg install --yes ${{ inputs.build-dependencies }}
        release: 13.1
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=$(sysctl -n hw.ncpu)
          cmake -B build -S . \
            -DCMAKE_LIBRARY_PATH:PATH=/usr/local/lib \
            -DENABLE_TESTS:BOOL=ON
          cmake --build build
          ctest --test-dir build
          cmake --install build
        usesh: true
