---
inputs:
  build-dependencies:
    default:  >-
      apache24
      bash
      boost-all
      cairo
      ceph14
      cmake
      coreutils
      curl
      freetype2
      gdal
      glib
      gmake
      harfbuzz
      icu
      iniparser
      libjpeg-turbo
      libmemcached
      libxml2
      png
      proj
      python39
      sqlite3
      tiff
      webp
      zlib-ng
    description: List of build dependency package(s) to install
  mapnik-version:
    default: 3.1.0
    description: Version of Mapnik to build & install
  python-version:
    default: 3.9
    description: Version of Python

runs:
  using: composite
  steps:
    - name: Create `Mapnik` source directory
      run: |
        mkdir mapnik-src
      shell: bash --noprofile --norc -euxo pipefail {0}

    - name: Cache `Mapnik` source directory
      id: cache-mapnik-src
      uses: actions/cache@v3
      with:
        path: mapnik-src
        key: freebsd-vm:0.3.0-LLVM-mapnik-${{ inputs.mapnik-version }}

    - name: Download `Mapnik`
      run: |
        curl --location --silent \
          https://github.com/mapnik/mapnik/releases/download/v${{ inputs.mapnik-version }}/mapnik-v${{ inputs.mapnik-version }}.tar.bz2 \
          | tar --extract --bzip2 --strip-components=1 --file=-
        curl --location --silent \
          https://github.com/mapnik/mapnik/commit/81103491b467e17218140f50bc0bb9dc8c1f0317.patch \
          | patch -F3 -Np1
      shell: bash --noprofile --norc -euxo pipefail {0}
      working-directory: mapnik-src
      if: steps.cache-mapnik-src.outputs.cache-hit != 'true'

    - name: Cache dependency packages
      uses: actions/cache@v3
      with:
        path: pkgs
        key: freebsd-vm:0.3.0-pkgs

    - name: Install dependencies, Build, Test & Install `mod_tile`
      uses: vmactions/freebsd-vm@v0.3.0
      with:
        mem: 4096
        prepare: |
          setenv PKG_CACHEDIR ${GITHUB_WORKSPACE}/pkgs
          pkg install --yes ${{ inputs.build-dependencies }}
          pkg upgrade --yes
          set JOBS=`sysctl -n hw.ncpu`
          setenv JOBS ${JOBS}
          setenv PROJ_LIB /usr/local/share/proj
          setenv PYTHON python${{ inputs.python-version }}
          cd ${GITHUB_WORKSPACE}/mapnik-src
          bash configure \
            FAST=True \
            HB_INCLUDES=/usr/local/include/harfbuzz \
            HB_LIBS=/usr/local/lib \
            ICU_INCLUDES=/usr/local/include \
            ICU_LIBS=/usr/local/lib \
            OPTIMIZATION=0 \
            PROJ_INCLUDES=/usr/local/include/proj \
            PROJ_LIBS=/usr/local/lib
          gmake PYTHON=${PYTHON}
          gmake install PYTHON=${PYTHON}
        release: 13.1
        run: |
          cmake -S . -B build -DCMAKE_LIBRARY_PATH=/usr/local/lib -DENABLE_TESTS=1
          cmake --build build
          ctest --test-dir build
          cmake --install build
