#!/bin/sh
#
# Plugin to monitor queue length of tiles submited for rendering in renderd
#
# Parameters: 
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [ "$1" = "config" ]; then

	echo 'graph_title Renderd queue length'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel metatiles'
	echo 'graph_category renderd'
	echo 'req.label Request Queue'
	echo 'req.type GAUGE'
	echo 'req.max 100'
	echo 'dirty.label Dirty Queue'
	echo 'dirty.type GAUGE'
	echo 'dirty.max 1000'
	exit 0
fi

reqlength=`sed -e '/^ReqQueueLength/!d' -e 's/.*: //' -e q /var/run/renderd/renderd.stats`
dirtlength=`sed -e '/^DirtQueueLength/!d' -e 's/.*: //' -e q /var/run/renderd/renderd.stats`

echo "req.value " $reqlength
echo "dirty.value " $dirtlength
