#!/bin/sh
#
# Plugin to monitor the rendering throughput of Renderd
#
# Parameters: 
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

if [ "$1" = "config" ]; then

	echo 'graph_title Renderd throughput'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Metatiles per ${graph_period}'
	echo 'graph_category renderd'
	echo 'graph_info Displays the number of metatiles being rendered by renderd per ${graph_period}'
	echo 'req.label Request Queue'
	echo 'req.type DERIVE'
	echo 'req.min 0'
	echo 'req.draw AREA'
	echo 'req.info Throughput of Metatiles submitted for on the fly rendering'
	echo 'dirty.label Dirty Queue'
	echo 'dirty.type DERIVE'
	echo 'dirty.min 0'
	echo 'dirty.draw STACK'
	echo 'dirty.info Throughput of dirty Metatiles submitted for re-render'
	echo 'dropped.label Dropped (x20)'
	echo 'dropped.type DERIVE'
	echo 'dropped.min 0'
	echo 'dropped.draw LINE2'
	echo 'dropped.info Number of Tiles dropped due to queue overload (x20)'
	echo 'dropped.cdef dropped,20,/'
	exit 0
fi

reqprocessed=`sed -e '/^ReqRendered/!d' -e 's/.*: //' -e q /var/run/renderd/renderd.stats`
dirtprocessed=`sed -e '/^DirtyRendered/!d' -e 's/.*: //' -e q /var/run/renderd/renderd.stats`
dropped=`sed -e '/^DropedRequest/!d' -e 's/.*: //' -e q /var/run/renderd/renderd.stats`

echo "req.value " $reqprocessed
echo "dirty.value " $dirtprocessed
echo "dropped.value " $dropped

#  LocalWords:  reqprocessed ReqRendered dirtprocessed DirtyRendered req
#  LocalWords:  DropedRequest
