.TH RENDER_LIST "1" "2024-02-06" "mod_tile v0.7.0"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
render_list \- renders a list of map tiles by sending requests to a rendering daemon.

.SH SYNOPSIS
.B render_list
.RI [ options ] <  "render.list"
.BR

.SH DESCRIPTION
This manual page briefly documents the
.B render_list
command.
.PP
.B render_list
is a helper utility that takes a list of map tiles from stdin and sends the requests to a rendering daemon
.PP

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
\fB\-a\fR|\-\-all
Render all tiles in given zoom level range instead of reading from STDIN.
.TP
\fB\-f\fR|\-\-force
Render tiles even if they seem current.
.TP
\fB\-m\fR|\-\-map=MAP
Render tiles in this map (defaults to 'default').
.TP
\fB\-l\fR|\-\-max-load=LOAD
Sleep if load is this high (defaults to 16).
.TP
\fB\-s\fR|\-\-socket=SOCKET|HOSTNAME:PORT
Unix domain socket name or hostname and port for contacting renderd.
.TP
\fB\-n\fR|\-\-num-threads=N
The number of parallel request threads (default 1).
.TP
\fB\-t\fR|\-\-tile-dir
Tile cache directory (defaults to '/var/cache/renderd/tiles').
.TP
\fB\-z\fR|\-\-min-zoom=ZOOM
Filter input to only render tiles greater or equal to this zoom level (default is 0).
.TP
\fB\-Z\fR|\-\-max-zoom=ZOOM
Filter input to only render tiles less than or equal to this zoom level (default is 20).
.PP
If you are using --all, you can restrict the tile range by adding these options:
.BR
  (please note that tile coordinates must be positive integers and are not latitude and longitude values)
.BR
  -x, --min-x=X        minimum X tile coordinate
.BR
  -X, --max-x=X        maximum X tile coordinate
.BR
  -y, --min-y=Y        minimum Y tile coordinate
.BR
  -Y, --max-y=Y        maximum Y tile coordinate
.PP
Without --all, send a list of tiles to be rendered from STDIN in the format:
.BR
  X Y Z
.BR
e.g.
.BR
  0 0 1
.BR
  0 1 1
.BR
  1 0 1
.BR
  1 1 1
.BR
The above would cause all 4 tiles at zoom 1 to be rendered
.TP
\fB\-h\fR|\-\-help
Print out a help text for render_list
.TP
\fB\-V\fR|\-\-version
Print out the version number for render_list
.PP

.SH SEE ALSO
.BR renderd(1)
.BR

.SH AUTHOR
render_list was written by OpenStreetMap project members.
.PP
This manual page was written by OpenStreetMap authors.
