.TH SPEEDTEST 1 "Jan 25, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
speedtest \- Benchmapr tile rendering with renderd.
.SH SYNOPSIS
.B speedtest
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B speedtest
command.
.PP
.B speedtest
renders a bunch of tiles at various zoom levels to benchmark the speed of the rendering.
.PP
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
\fB\-s\fR|\-\-socket=SOCKET
Specify the location of the renderd socket to connect to.
.TP
\fB\-m\fR|\-\-map=MAP
Specify the rendering style to test. The default is "default"
.PP
.SH SEE ALSO
.BR renderd (1),
.br
.SH AUTHOR
speedtest was written by Jon Burgess and other
OpenStreetMap project members.
.PP
This manual page was written by OpenStreetMap authors.
