.TH CONVERT_META 1 "Jan 25, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
convert_meta \- A conversion program from .png map tiles to a more efficient conglomerate format (.meta).
.SH SYNOPSIS
.B convert_meta 
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B convert_meta
command.
.PP
.B convert_meta
converts individual .png map tiles into the more efficient .meta file format. The .meta
format stores a grid of 8x8 tiles in a single meta tile, reducing the number of files by
a factor of 64.
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
\fB\-t\fR|\-\-tile-dir
Specify the base directory where the tiles are stored. The default is /var/lib/mod_tile
.TP
\fB\-m\fR|\-\-map
Specify the map style to convert. This specifies the full path to the files and is relative to the tile directory.
The default is "default" and results in a full path of /var/lib/mod_tile/default to search for the tiles to convert
.TP
\fB\-u\fR|\-\-unpack
Unpack the .meta files back to PNGs
.TP
\fB\-z\fR|\-\-min-zoom
Specify the smallest zoom level to process. The default is 0.
.TP
\fB\-Z\fR|\-\-max-zoom
Specify the largest zoom level up to which to  process tiles. The default is 18.
.PP
.SH AUTHOR
convert_meta was written by Jon Burgess and other
OpenStreetMap project members.
.PP
This manual page was written by OpenStreetMap authors.
