.TH RENDERD 1 "Jan 25, 2012"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
renderd \- Rendering daemon for rendering OpenStreetMap tiles.
.SH SYNOPSIS
.B renderd
.RI [ options ]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B renderd
command.
.PP
.B renderd
is a rendering daemon for map tiles with the mapnik library. It receives render requests
on a socket. Renderd queues requests in a number of different queues to manage load while 
rendering the requests with the mapnik library. By default renderd will start as a daemon.
It will log information in the syslog.
.PP
.SH OPTIONS
This programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
\fB\-f\fR|\-\-foreground
Run renderd in the foreground for debugging purposes.
.TP
\fB\-c\fR|\-\-config
Set the location of the config file used to configure the various parameters of renderd,
like the mapnik style sheet. The default is /etc/renderd.conf
.TP
\fB\-s\fR|\-\-slave
Renderd can be used in a distributed fashion accross multiple rendering servers. The master renderd handles queuing and
passes requests to the slaves. This parameter specifies which of the slave sections of renderd.conf applies to this instance
of renderd. The default is to use the master section
.TP
\fB\-h\fR|\-\-help
Print out a help text for renderd
.PP
.SH SEE ALSO
.BR renderd.conf (1),
.br
.SH AUTHOR
renderd was written by Jon Burgess, and other OpenStreetMap project members.
.PP
This manual page was written by OpenStreetMap authors.
