---
name: Build & Test (Mapnik >= 4)

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-test-mapnik-4:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'debian:11'
        on_default_branch:
          - ${{ contains(github.ref, 'master') }}
        include:
          - image: 'ubuntu:22.04'
        exclude:
          - on_default_branch: false
      fail-fast: false
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout `mod_tile`
        uses: actions/checkout@v3

      - name: Install Dependencies (Debian)
        uses: ./.github/actions/apt-get/install
        with:
          packages: >-
            ${{ env.debian-build-dependencies }}
            ${{ env.debian-mapnik-build-dependencies }}
            ${{ env.debian-test-dependencies }}
        if: ${{ startsWith(matrix.image, 'debian:') }}

      - name: Install Dependencies (Ubuntu)
        uses: ./.github/actions/apt-get/install
        with:
          packages: >-
            ${{ env.ubuntu-build-dependencies }}
            ${{ env.ubuntu-mapnik-build-dependencies }}
            ${{ env.ubuntu-test-dependencies }}
        if: ${{ startsWith(matrix.image, 'ubuntu:') }}

      - name: Checkout `mapnik`
        uses: actions/checkout@v3
        with:
          path: mapnik
          repository: mapnik/mapnik
          submodules: recursive

      - name: Build `mapnik`
        run: |
          export CMAKE_BUILD_PARALLEL_LEVEL=${BUILD_PARALLEL_LEVEL:-$(nproc)}
          cmake -S mapnik -B mapnik-build \
            -DBUILD_DEMO_VIEWER:BOOL=OFF \
            -DBUILD_TESTING:BOOL=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX:PATH=/usr
          cmake --build mapnik-build

      - name: Install `mapnik`
        run: cmake --install mapnik-build

      - name: Build `mod_tile`
        uses: ./.github/actions/build

      - name: Install `mod_tile`
        uses: ./.github/actions/install

      - name: Configure Apache HTTP Server
        uses: ./.github/actions/apache/configure

      - name: Test `mod_tile`
        uses: ./.github/actions/test
        timeout-minutes: 5

env:
  debian-build-dependencies: >-
    apache2-dev
    libcairo2-dev
    libcurl4-gnutls-dev
    libglib2.0-dev
    libiniparser-dev
    libmemcached-dev
    librados-dev
  debian-test-dependencies: >-
    apache2
    libjs-leaflet
  debian-mapnik-build-dependencies: >-
    cmake
    git
    libboost-filesystem-dev
    libboost-program-options-dev
    libboost-regex-dev
    libfreetype6-dev
    libgdal-dev
    libharfbuzz-dev
    libicu-dev
    libjpeg-dev
    libpq-dev
    libproj-dev
    libsqlite3-dev
    libtiff-dev
    libwebp-dev
    libxml2-dev
    postgresql-server-dev-all
  ubuntu-build-dependencies: >-
    apache2-dev
    libcairo2-dev
    libcurl4-gnutls-dev
    libglib2.0-dev
    libiniparser-dev
    libmemcached-dev
    librados-dev
  ubuntu-test-dependencies: >-
    apache2
    libjs-leaflet
  ubuntu-mapnik-build-dependencies: >-
    cmake
    git
    libboost-filesystem-dev
    libboost-program-options-dev
    libboost-regex-dev
    libfreetype6-dev
    libgdal-dev
    libharfbuzz-dev
    libicu-dev
    libjpeg-dev
    libpq-dev
    libproj-dev
    libsqlite3-dev
    libtiff-dev
    libwebp-dev
    libxml2-dev
    postgresql-server-dev-all
