---
name: Build & Test (CentOS 7)

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Lint

env:
  build-dependencies: >-
    cairo-devel
    glib2-devel
    httpd-devel
    iniparser-devel
    libcurl-devel
    libmemcached-devel
    librados2-devel
    mapnik-devel

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: centos:7
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Provision environment
        uses: ./.github/actions/yum/provision/centos-7
        with:
          packages: ${{ env.build-dependencies }}
      - name: Link `iniparser.h` to `iniparser/iniparser.h`
        run: |
          mkdir /usr/include/iniparser
          ln -s /usr/include/iniparser.h /usr/include/iniparser/iniparser.h
      - name: Run `./autogen.sh`
        run: ./autogen.sh
      - name: Run `./configure`
        run: ./configure
      - name: Run `make`
        run: make
      - name: Create build archive
        uses: ./.github/actions/build-archive/create
      - name: Upload build archive
        uses: actions/upload-artifact@v2
        with:
          name: build-archive
          path: /tmp/workspace.tar.gz
          retention-days: 1

  test-make-test:
    name: Test with `make test`
    runs-on: ubuntu-latest
    container:
      image: centos:7
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Provision environment
        uses: ./.github/actions/yum/provision/centos-7
        with:
          packages: ${{ env.build-dependencies }}
      - name: Link `iniparser.h` to `iniparser/iniparser.h`
        run: |
          mkdir /usr/include/iniparser
          ln -s /usr/include/iniparser.h /usr/include/iniparser/iniparser.h
      - name: Download build archive
        uses: actions/download-artifact@v2
        with:
          name: build-archive
          path: /tmp
      - name: Extract build archive
        uses: ./.github/actions/build-archive/extract
      - name: Run `make test`
        run: make test

  test-mod_tile-module:
    name: Test `mod_tile` module
    runs-on: ubuntu-latest
    container:
      image: centos:7
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Provision environment
        uses: ./.github/actions/yum/provision/centos-7
        with:
          packages: ${{ env.build-dependencies }} httpd
      - name: Link `iniparser.h` to `iniparser/iniparser.h`
        run: |
          mkdir /usr/include/iniparser
          ln -s /usr/include/iniparser.h /usr/include/iniparser/iniparser.h
      - name: Download build archive
        uses: actions/download-artifact@v2
        with:
          name: build-archive
          path: /tmp
      - name: Extract build archive
        uses: ./.github/actions/build-archive/extract
      - name: Configure Apache HTTP Server
        run: |
          mkdir --parents /usr/share/javascript/leaflet
          curl --silent \
            "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.js" \
            > /usr/share/javascript/leaflet/leaflet.min.js
          curl --silent \
            "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.css" \
            > /usr/share/javascript/leaflet/leaflet.css
          mkdir --parents /run/renderd /var/cache/renderd/tiles
          ln --symbolic \
            "${PWD}/utils/example-map" \
            /var/www/
          ln --symbolic \
            /usr/share/javascript/leaflet \
            /var/www/example-map/leaflet
          ln --symbolic \
            "${PWD}/etc/renderd/renderd.conf.examples" \
            /etc/renderd.conf
          ln --symbolic \
            "${PWD}/etc/apache2/renderd.conf" \
            /etc/httpd/conf.d/renderd.conf
          ln --symbolic \
            "${PWD}/etc/apache2/renderd-example-map.conf" \
            /etc/httpd/conf.d/renderd-example-map.conf
          echo "LoadModule tile_module /usr/lib64/httpd/modules/mod_tile.so" \
            | tee --append /etc/httpd/conf.modules.d/11-mod_tile.conf
          sed --in-place \
            "s#/usr/lib/mapnik/3.0/input#/usr/lib64/mapnik/input#g" \
            /etc/renderd.conf
          sed --in-place \
            "s#/usr/share/fonts/truetype#/usr/share/fonts#g" \
            /etc/renderd.conf
          rm --force /etc/httpd/conf.d/welcome.conf
      - name: Run `make install`
        run: make install
      - name: Run `make install-mod_tile`
        run: make install-mod_tile
      - name: Start `renderd`
        run: renderd
      - name: Start Apache HTTP Server
        run: httpd
      - name: Test Apache HTTP Server `mod_tile` module
        run: |
          curl --silent http://localhost/renderd-example/tiles/9/297/191.png \
            | sha224sum - \
            | grep 9cd82e5af9d9002a1c75126ebdb7bf054ec0b7ed0db228dfb0a09bae
