---
name: Coverage

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - "*CI"

jobs:
  Coverage:
    name: >-
      Build, Test & Report Coverage
      ${{ matrix.mapnik_latest && '(Latest Mapnik)' || '' }}
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
      CFLAGS: --coverage
      CXXFLAGS: --coverage
      TEST_PARALLEL_LEVEL: 1
    strategy:
      matrix:
        compiler:
          - GNU
        mapnik_latest:
          - false
          - true
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/dependencies/install
        with:
          ubuntu-mapnik-latest-build-dependencies: >-
            cmake
            git
            libboost-filesystem-dev
            libboost-program-options-dev
            libboost-regex-dev
            libfreetype6-dev
            libgdal-dev
            libharfbuzz-dev
            libicu-dev
            libjpeg-dev
            libpq-dev
            libproj-dev
            libsqlite3-dev
            libtiff-dev
            libwebp-dev
            libxml2-dev

      - name: Build `mod_tile`
        uses: ./.github/actions/cmake/build

      - name: Test `mod_tile`
        uses: ./.github/actions/cmake/test

      - name: Process & Report `mod_tile` coverage results
        uses: ./.github/actions/coverage

      - name: Write coverage summary to `$GITHUB_STEP_SUMMARY`
        run: lcov --summary build/coverage.info | sed 's/^  /* /g' >> ${GITHUB_STEP_SUMMARY}

      - name: Generate `mod_tile` coverage results artifact
        run: |
          mkdir -p coverage
          genhtml coverage.info --output-directory coverage/${{ matrix.mapnik_latest && 'mapnik_latest' || 'mapnik' }}
        working-directory: build

      - name: Upload `mod_tile` coverage results artifact
        uses: actions/upload-artifact@v3
        with:
          name: Coverage Results
          path: build/coverage
