---
name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - develop

env:
  test-dependencies: >-
    astyle

jobs:
  astyle:
    name: Lint with `astyle`
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Provision environment
        uses: ./.github/actions/apt-get/install
        with:
          packages: >-
            ${{ env.test-dependencies }}
      - name: Check if any modifications were made by `astyle`
        run: |
          ASTYLE_CMD="astyle \
            --break-blocks \
            --indent-switches \
            --indent=force-tab=8 \
            --lineend=linux \
            --options=none \
            --pad-header \
            --pad-oper \
            --style=1tbs \
            --suffix=none \
            --unpad-paren \
            includes/* src/*"
          ASTYLE_OUTPUT=$(${ASTYLE_CMD} --dry-run)
          if [ -n "$(echo "${ASTYLE_OUTPUT}" | grep -v "Unchanged")" ]; then
            echo "The following files are in need of formatting:"
            echo "${ASTYLE_OUTPUT}" | grep -v "Unchanged" | awk '{print "\t"$2}'
            echo "Run the following command before submitting a pull request:"
            printf "\t${ASTYLE_CMD}\n" | tr -s ' '
            exit 1
          fi
